// <auto-generated />
namespace RpgGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fail_to_job_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fail_to_job_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201712291244468_fail_to_job_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
