// <auto-generated />
namespace RpgGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_character_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_character_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201712290904202_test_character_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
