// <auto-generated />
namespace RpgGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_job_as_char_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_job_as_char_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201712291237187_test_job_as_char_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
